services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - app-network

  frontend:
    image: node:24-alpine
    container_name: fe
    working_dir: /app
    volumes:
      - ./packages/fe:/app
      - ./packages/shared:/shared
      - fe_node_modules:/app/node_modules
      - fe_pnpm_store:/root/.local/share/pnpm/store
    ports:
      - "4201:4200"
    command: >-
      sh -c "corepack enable && pnpm --dir /shared install && pnpm --dir /shared run build && pnpm install && pnpm run start:prod"
    environment:
      - NODE_ENV=production
      - NODE_PATH=/app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "3009:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app-network

  backend:
    image: node:24-alpine
    container_name: be
    working_dir: /app
    volumes:
      - ./packages/be:/app
      - ./packages/shared:/shared
      - be_node_modules:/app/node_modules
      - be_pnpm_store:/root/.local/share/pnpm/store
    ports:
      - "3008:3000"
    command: sh -c "corepack enable && pnpm i && pnpm run start:prod"
    environment:
      - NODE_ENV=production
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - NODE_PATH=/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  fe_node_modules:
  fe_pnpm_store:
  be_node_modules:
  be_pnpm_store:
